language: python
python:
    - 3.8

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
addons:
    apt:
        packages:
            - blender

before_install:
    - sudo apt-get -y update
    - sudo apt-get install -y ffmpeg python3-coverage

install:
    - BLENDER_VERSION="2.91"
    - BLENDER_BASE="blender-${BLENDER_VERSION}.0-linux64"
    - BLENDER_TARBALL="${BLENDER_BASE}.tar.xz"
    - mkdir blender_build && cd blender_build
    - wget http://ftp.nluug.nl/pub/graphics/blender/release/Blender${BLENDER_VERSION}/${BLENDER_TARBALL}
    - tar xf ${BLENDER_TARBALL}
    - mv ${BLENDER_BASE} blender
    - rm ${BLENDER_TARBALL}
    - cd ..
    - pip install -r tests/requirements.txt

script:
    - PATH="blender_build/blender:${PATH}"
    - blender_build/blender/blender --version
    - sh tests/run.sh

after_success:
    - codecov -f tests_output/coverage.xml

notifications:
    email:
        on_success: change
        on_failure: always
